### ISSUE TITLE
Are these projects outdated already?

### ISSUE THREAD

**Issue by WestXu** [Microsoft/Windows-Packaging-Samples#1]
For example, in the solution ShareTarget, I can't add the Windows reference in the WpfPhotoViewer project. It seems not listed on the reference list anymore. So how can I call a uwp window from winforms or wpf applications now?

**Comment by rido-min** [comment]
hi @WestXu (sorry for the delay)

The Windows references are not available in the References Dialog. This [doc](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-enhance) explains how to add those references.

**Comment by ali-h2010** [comment]
@rido-min , i updated Visual Studio and Windows SDK to latest version but i am getting "This project is outdated, do you want to build it?" 

when i build it , it runs fine but the even is not triggering and i am not seeing any notifications!

**Comment by rido-min** [comment]
Hi @ali-h2010  a lot of things have changed in the last year. Can you provide repro steps to understand what is not working? The sample "Share Target" does not show any notification, it's meant to describe how to integrate the "Share target" action.

**Comment by ali-h2010** [comment]
@rido-min , sorry for the confusion. 
I was actually talking about BGTask.
I just downloaded the solution, restored the libraries, and run the solution.

**Comment by rido-min** [comment]
IIRC you need to click the button to register the background task, then wait some time until the notification is hit.
