### ISSUE TITLE
SystrayExtension: System.InvalidOperationException: The process has no package identity

### ISSUE THREAD

**Issue by nollexu** [Microsoft/Windows-Packaging-Samples#3]
![image](https://user-images.githubusercontent.com/34390589/54104213-f6f29c00-4409-11e9-8fdb-8f6eaf0c427f.png)

**Comment by rido-min** [comment]
This error usually happens when you start the Win32 project, so the EXE is not running in the centennial container. Can you try to set your startup project to the Packaging Project?

**Comment by rido-min** [comment]
@nollexu  I'm closing this issue due to the lack of inactivity, if you hit the same issue when starting the packaging project please reopen this issue.
