### ISSUE TITLE
Would it be possible to get an in-process app service example?

### ISSUE THREAD

**Issue by csuzw** [Microsoft/Windows-Packaging-Samples#4]
There are some old samples/tutorials of in-process app services but I can't find a single one that uses the Windows Packaging approach.  I have been trying to get this working with no luck (https://github.com/csuzw/AppServiceTest).

**Comment by rido-min** [comment]
If the Win32 process references a WinRT component, the in-proc server registrations would be added to the package manifest. 

Would this scenario satisfy your needs?

**Comment by rido-min** [comment]
@csuzw  is this sample https://github.com/microsoft/Windows-Packaging-Samples/blob/82470835aed02db693d34e96dc4259efaedcc295/OfficeInterop/Excel.Interop/Program.cs#L38 what you are looking for?

**Comment by rido-min** [comment]
Sample added https://github.com/microsoft/Windows-Packaging-Samples/commit/56b56e4b11bbf1156ff469388b9c8af41b3ac6fc
