### ISSUE TITLE
Error in VS 2019

### ISSUE THREAD

**Issue by mjfusa** [Microsoft/Windows-Packaging-Samples#5]
I am getting this error when building BGTask in VS 2019.

3>------ Build started: Project: WPFUIWithBackgroundTask.Package, Configuration: Debug x64 ------
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'UWPHead.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='AnyCPU'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.
3>Done building project "UWPHead.csproj" -- FAILED.

Can you help me fix?

**Comment by rido-min** [comment]
can you try to build for a specific platform such as x64 or x86? 

I'm leaving this issue open to delete Any CPU references.

**Comment by rido-min** [comment]
I've updated the CI build based on yaml, and you can see the build succeeds with VS2019 so I'm closing this issue
