### ISSUE TITLE
System.Exception: 'Element not found'

### ISSUE THREAD

**Issue by ali-h2010** [Microsoft/Windows-Packaging-Samples#9]
I am getting the following error:
System.Exception: 'Element not found. (Exception from HRESULT: 0x80070490)'

On this line:
https://github.com/microsoft/Windows-Packaging-Samples/blob/d91042e2e022306ea1993bb8c5c0551df45ad140/BGTask/WpfUIWithBackgroundTask/UWPBackgroundTaskCatalog.cs#L14

is there any set up needed?

**Comment by rido-min** [comment]
Hi @ali-h2010 
Can you provide repro steps? The background task is registered through the Package manifest, hence you might need to star debugging from the packaging project.

Which versions of VS, Windows and SDK are you using?

**Comment by ali-h2010** [comment]
After running the packaging project i got the real error which was missing SDK
